Name: queue-proxy
Host: 0.0.0.0
Port: 8080

########################################################################
# meta:
Meta:
  Name: 'queue.proxy'
  Version: '0.0.1'

DB:
  Demo: 'todo'

Cache:
  Demo: 'todo'

MQ:
  Demo:
    Url: 'amqp://rabbit:rabbit@localhost:5672/exchange_server'
    Timeout: '5s'

RPC:
  Demo: 'todo'

HTTP:
  Demo: 'todo'


# graphql:
GraphQL:
  Url42: 'http://34.87.21.221:8000/subgraphs/name/SkyWalker'
  Url: 'http://34.87.21.221:8000/subgraphs/name/SkyWalker'
  NetworkID: 42      # 主网编号
  BlockStart: 10000  # 起始块高度
  QueryInterval: 12  # 12s


Job:
  IntervalMinute: 1 # 1min
  TickerSecond: 5   # 5s
  SlotNum: 600      # 600个 task slot
  SleepDuration: 1  #
