Name: queue-proxy
Host: 0.0.0.0
Port: 8080

########################################################################
# meta:
Meta:
  Name: 'queue.proxy'
  Version: '0.0.1'

DB:
  Demo: 'todo'

Cache:
  Demo: 'todo'

MQ:
  Demo:
    Url: 'amqp://rabbit:rabbit@localhost:5672/exchange_server'
    Timeout: '5s'

RPC:
  Demo: 'todo'

HTTP:
  Demo: 'todo'



